[Rainmeter]
Update=-1
AccurateText=1
DynamicVariables=1

[Variables]
@include=#@#variables.inc

[Metadata]
Name=SideBarLauncher-Minimal - Witcher edition
Author= ltszatyi
Information=My first published launcher skin inspired by Witcher 3 wallpaper (Credits:Daniel Valaisis CDPR https://www.artstation.com/artwork/8wLxOx). Listed Apps: Control Panel, My Computer, Google Chrome, Steam, Discord, Spotify. Contact: https://www.deviantart.com/ltszatyi
Version=1.01

[BackgroundRectangle]
Meter = Shape
Shape = Rectangle 0,0,56,340,18,18 | Fill Color #Color3# | StrokeWidth 1 | Stroke LinearGradient Gradient
Gradient= 170 | 209, 182, 80, 255 ; 1 | 150,150,150,20 ; 0,9
ClickThrough=1
;
;
; Hints:
; If you change any app insert path or shell command to "LeftMouseDownAction" variable.
; If you change app logo make sure it is white colored .PNG file in common rectangle sizes 24,32,48,64,128 etc.
;
;
[Icon1]
;Settings COG - Control Panel
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\settings.png
X=18
Y=20
W=20
AntiAlias=1
ImageTint=#White#
LeftMouseDownAction=Control Panel
MouseOverAction=[!SetOption Icon1 ImageTint #Color1#][!SetOption Icon1 W 32][!SetOption Icon1 X 12][!SetOption Icon1 Y 18][!SetOption MeterTextIcon1 Hidden 0][!Update]
MouseLeaveAction=[!SetOption Icon1 ImageTint #White#][!SetOption Icon1 W 20][!SetOption Icon1 X 18][!SetOption Icon1 Y 20][!SetOption MeterTextIcon1 Hidden 1][!Update]

[MeterTextIcon1]
Meter=String
Text="Evil is Evil."
StringAlign=Left
FontFace=Sylfaen
FontColor=#White#
FontSize=13
X=([Icon1:X]+60)
Y=([Icon1:Y]+3)
AntiAlias=1
Hidden=1

[Icon2]
;My PC
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\computer.png
X=16
Y=68
W=24
AntiAlias=1
ImageTint=#White#
LeftMouseDownAction= [Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
MouseOverAction=[!SetOption Icon2 ImageTint #Color1#][!SetOption Icon2 W 32][!SetOption Icon2 X 12][!SetOption Icon2 Y 65][!SetOption MeterTextIcon2 Hidden 0][!Update]
MouseLeaveAction=[!SetOption Icon2 ImageTint #White#][!SetOption Icon2 W 24][!SetOption Icon2 X 16][!SetOption Icon2 Y 68][!SetOption MeterTextIcon2 Hidden 1][!Update]

[MeterTextIcon2]
Meter=String
Text="Hmm."
StringAlign=Left
FontFace=Sylfaen
FontColor=#White#
FontSize=13
X=([Icon2:X]+60)
Y=([Icon2:Y]+2)
AntiAlias=1
Hidden=1

[Icon3]
;Browser of your choice
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\browser.png
X=16
Y=124
W=24
AntiAlias=1
ImageTint=#White#
LeftMouseDownAction=["C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Default"]
MouseOverAction=[!SetOption Icon3 ImageTint #Color1#][!SetOption Icon3 W 32][!SetOption Icon3 X 12][!SetOption Icon3 Y 120][!SetOption MeterTextIcon3 Hidden 0][!Update]
MouseLeaveAction=[!SetOption Icon3 ImageTint #White#][!SetOption Icon3 W 24][!SetOption Icon3 X 16][!SetOption Icon3 Y 124][!SetOption MeterTextIcon3 Hidden 1][!Update]

[MeterTextIcon3]
Meter=String
Text="Hmm. Idiots, the lot of them."
StringAlign=Left
FontFace=Sylfaen
FontColor=#White#
FontSize=13
X=([Icon3:X]+60)
Y=([Icon3:Y]+2)
AntiAlias=1
Hidden=1

[Icon4]
;Steam
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\steam.png
X=16
Y=180
W=24
AntiAlias=1
ImageTint=#White#
LeftMouseDownAction=["C:\Program Files (x86)\Steam\steam.exe"]
MouseOverAction=[!SetOption Icon4 ImageTint #Color1#][!SetOption Icon4 W 32][!SetOption Icon4 X 12][!SetOption Icon4 Y 178][!SetOption MeterTextIcon4 Hidden 0][!Update]
MouseLeaveAction=[!SetOption Icon4 ImageTint #White#][!SetOption Icon4 W 24][!SetOption Icon4 X 16][!SetOption Icon4 Y 180][!SetOption MeterTextIcon4 Hidden 1][!Update]

[MeterTextIcon4]
Meter=String
Text="Tired of life."
StringAlign=Left
FontFace=Sylfaen
FontColor=#White#
FontSize=13
X=([Icon4:X]+60)
Y=([Icon4:Y]+2)
AntiAlias=1
Hidden=1

[Icon5]
;Discord
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\discord.png
X=18
Y=234
W=21
AntiAlias=1
ImageTint=#White#
LeftMouseDownAction=["C:\Program Files (x86)\Discord\discord.exe"]
MouseOverAction=[!SetOption Icon5 ImageTint #Color1#][!SetOption Icon5 W 28][!SetOption Icon5 X 14][!SetOption Icon5 Y 230][!SetOption MeterTextIcon5 Hidden 0][!Update]
MouseLeaveAction=[!SetOption Icon5 ImageTint #White#][!SetOption Icon5 W 21][!SetOption Icon5 X 18][!SetOption Icon5 Y 234][!SetOption MeterTextIcon5 Hidden 1][!Update]

[MeterTextIcon5]
Meter=String
Text="Oh, that's rough. Sympathies."
StringAlign=Left
FontFace=Sylfaen
FontColor=#White#
FontSize=13
X=([Icon5:X]+60)
Y=([Icon5:Y]+2)
AntiAlias=1
Hidden=1

[Icon6]
;Spotify
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\spotify.png
X=20
Y=286
W=20
AntiAlias=1
ImageTint=#White#
LeftMouseDownAction=["C:\Program Files\Spotify\Spotify.exe"]
MouseOverAction=[!SetOption Icon6 ImageTint #Color1#][!SetOption Icon6 W 28][!SetOption Icon6 X 16][!SetOption Icon6 Y 282][!SetOption MeterTextIcon6 Hidden 0][!Update]
MouseLeaveAction=[!SetOption Icon6 ImageTint #White#][!SetOption Icon6 W 20][!SetOption Icon6 X 20][!SetOption Icon6 Y 286][!SetOption MeterTextIcon6 Hidden 1][!Update]

[MeterTextIcon6]
Meter=String
Text="Toss a coin to your Witcher.."
StringAlign=Left
FontFace=Sylfaen
FontColor=#White#
FontSize=13
X=([Icon6:X]+59)
Y=([Icon6:Y]+2)
AntiAlias=1
Hidden=1